// ==============================================================================
// features/roles-permissions/domain/entities/role-permission.matrix.ts
// Predefined Role-to-Permission Mapping Matrix
// ==============================================================================
import type { RoleCode, PermissionCode } from "./role.enums";

export const ALL_PERMISSIONS: PermissionCode[] = [
  "dashboard:view",
  "products:view",
  "products:create",
  "products:edit",
  "products:delete",
  "categories:view",
  "categories:create",
  "categories:edit",
  "categories:delete",
  "services:view",
  "services:create",
  "services:edit",
  "services:delete",
  "projects:view",
  "projects:create",
  "projects:edit",
  "projects:delete",
  "certificates:view",
  "certificates:create",
  "certificates:edit",
  "certificates:delete",
  "team:view",
  "team:create",
  "team:edit",
  "team:delete",
  "contact:view",
  "contact:edit",
  "contact:messages",
  "rfq:view",
  "rfq:update_status",
  "seo:view",
  "seo:edit",
  "settings:view",
  "settings:edit",
  "users:view",
  "users:create",
  "users:edit",
  "users:delete",
  "activity_log:view",
];

export const ROLE_PERMISSION_MATRIX: Record<RoleCode, PermissionCode[]> = {
  // Super Admin: Unrestricted access
  super_admin: ALL_PERMISSIONS,

  // Admin: Full management except user administration
  admin: [
    "dashboard:view",
    "products:view",
    "products:create",
    "products:edit",
    "products:delete",
    "categories:view",
    "categories:create",
    "categories:edit",
    "categories:delete",
    "services:view",
    "services:create",
    "services:edit",
    "services:delete",
    "projects:view",
    "projects:create",
    "projects:edit",
    "projects:delete",
    "certificates:view",
    "certificates:create",
    "certificates:edit",
    "certificates:delete",
    "team:view",
    "team:create",
    "team:edit",
    "team:delete",
    "contact:view",
    "contact:edit",
    "contact:messages",
    "rfq:view",
    "rfq:update_status",
    "seo:view",
    "seo:edit",
    "settings:view",
    "settings:edit",
    "users:view",
    "activity_log:view",
  ],

  // Editor: Create & Edit content. Cannot delete items or manage settings/users.
  editor: [
    "dashboard:view",
    "products:view",
    "products:create",
    "products:edit",
    "categories:view",
    "categories:create",
    "categories:edit",
    "services:view",
    "services:create",
    "services:edit",
    "projects:view",
    "projects:create",
    "projects:edit",
    "certificates:view",
    "certificates:create",
    "certificates:edit",
    "team:view",
    "team:create",
    "team:edit",
    "contact:view",
    "contact:edit",
    "contact:messages",
    "rfq:view",
    "rfq:update_status",
    "seo:view",
    "seo:edit",
    "activity_log:view",
  ],

  // Viewer: Read-only access across modules
  viewer: [
    "dashboard:view",
    "products:view",
    "categories:view",
    "services:view",
    "projects:view",
    "certificates:view",
    "team:view",
    "contact:view",
    "contact:messages",
    "rfq:view",
    "seo:view",
    "settings:view",
    "activity_log:view",
  ],
};
